import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/src/app/globals.scss";
import {StoreWrapper} from "@/src/app/store-wrapper";
import React from "react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <StoreWrapper>
      <div style={{display: "flex", justifyContent: "center", gap: '10px'}}>
        <Link href={'/'} >main</Link>
        <Link href={'/profile'} >profile</Link>
        <Link href={'/settings'} >settings</Link>
      </div>
      {children}
    </StoreWrapper>
    </body>
    </html>
  );
}
