import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/src/shared/styles/globals.scss'
import { StoreWrapper } from '@/src/store/store-wrapper'
import React from 'react'
import { AppLoader } from '@/src/shared/components/AppLoader/AppLoader'
import 'react-toastify/ReactToastify.css'
import { AlertSnackbar } from '@/src/shared/components/AlertSnackbar/AlertSnackbar'
import { Header } from '@/src/shared/components/Header/Header'
import '@rocketweb-studio/ulens-ui-kit/dist/index.css'
import {Sidebar} from "@/src/shared/components/Sidebar";
import {FlexContainer} from "@/src/shared/components/FlexContainer";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreWrapper>
          <Header />
          <FlexContainer>
            <Sidebar/>
            <main style={{flexGrow: 1}}>{children}</main>
          </FlexContainer>
          <AppLoader />
          <AlertSnackbar />
        </StoreWrapper>
      </body>
    </html>
  )
}
