import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/src/app/globals.scss";
// import '@/src/common/styles/colors.scss';
// import '@/src/common/styles/typography.scss';
import {StoreWrapper} from "@/src/app/store-wrapper";
import React from "react";
import {Navigation} from "@/src/common/components/Navigation/Navigation";
import {AppLoader} from "@/src/common/components/AppLoader/AppLoader";
import 'react-toastify/ReactToastify.css'
import {AlertSnackbar} from "@/src/common/components/AlertSnackbar/AlertSnackbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <StoreWrapper>
      <Navigation/>
      {children}
      <AppLoader />
      <AlertSnackbar/>
    </StoreWrapper>
    </body>
    </html>
  );
}
